<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>9.0</LangVersion>
    <RootNamespace>MyWorld.Bench</RootNamespace>
    <AssemblyName>MyWorld.Bench</AssemblyName>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\tools\dotnet\MyWorld.Core\MyWorld.Core.csproj" />
  </ItemGroup>

</Project>
